# Generated by Django 5.0.2 on 2024-06-17 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text="The player's username", max_length=100, verbose_name='Username')),
                ('score', models.IntegerField(default=0, help_text="The player's score", verbose_name='Score')),
            ],
        ),
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_score', models.IntegerField(verbose_name='Player 1 Score')),
                ('player2_score', models.IntegerField(verbose_name='Player 2 Score')),
                ('date_played', models.DateTimeField(auto_now_add=True, verbose_name='Date Played')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_games', to='game_pong.player', verbose_name='Player 1')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_games', to='game_pong.player', verbose_name='Player 2')),
            ],
        ),
    ]
