# Generated by Django 5.0.2 on 2024-06-20 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_pong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerecord',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_games', to='game_pong.player', verbose_name='Player 1'),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_games', to='game_pong.player', verbose_name='Player 2'),
        ),
    ]
